Сделал разметку страницы
htmlacademy-htmlcss/1750369-nerds-31 pull request #2
Opened 2021-05-23 21:17 UTC by Klyacsa

2021-05-24 15:16 UTC, ValeryKrukovich requested changes

2021-05-24 15:16 UTC, ValeryKrukovich commented on index.html
> +      <a href="blank.html">Корзина</a>
Делаешь ссылку на страницу, но не создал ее. Нужно создать, как говорилось в лайве, с шапкой подвалом, можно заголовком.

2021-05-24 15:16 UTC, ValeryKrukovich commented on index.html
> +      <button type="button">УЗНАТЬ БОЛЬШЕ</button>
Подумай это кнопка или ссылка? что будет происходить после нажатия?
Делай все надписи в нормально регистре, как в письме. В верхний регистр потом с помощью css  делается.
Возьми за правило себе.

Тут по тз будет слайдер, и верстка всех слайдов обязательна.
Посмотри в макетах есть слои скрытые.  И сама структура слайдера у тебя тогда поменяется

2021-05-24 15:16 UTC, ValeryKrukovich commented on index.html
> +  </header>
Делай в едином стиле, если между большими структурными блоками отступ, то делай его везде

2021-05-24 15:16 UTC, ValeryKrukovich commented on index.html
> +      <h2>Долго, дорого, скрупулезно.</h2>
Уверен что это именно заголовком хочешь сделать?

2021-05-24 15:16 UTC, ValeryKrukovich commented on index.html
> +        <h3>Веб-сайты</h3>
Используешь внутри секции сразу h3, нарушенно дерево заголовков.
 Предлагаю добавить h2 для секции-родителя

2021-05-24 15:16 UTC, ValeryKrukovich commented on index.html
> +      <h1>Мы — маленькая, но гордая дизайн-студия из Краснодара.</h1>
Уверен что это именно главный заголовок страницы всей?

2021-05-24 15:16 UTC, ValeryKrukovich commented on index.html
> +      <h2>Выполняем заказы на разработку:</h2>
Мне кажется это не совсем заголовок. Подумай, может он не нужен тут

2021-05-24 15:16 UTC, ValeryKrukovich commented on index.html
> +      <h2>с 2004 года Любим точность во всем:</h2>
То же, по смыслу не соглашусь с тобой что это заголовок

2021-05-24 15:16 UTC, ValeryKrukovich commented on index.html
> +    <article>
Тут явная ошибка в использовании этого семантического тега. Плюс обертка в виде этого тега - лишняя.
Ответь себе, что делает этот тег в данном месте?

2021-05-24 15:16 UTC, ValeryKrukovich commented on index.html
> +      <section>
Тут немного поехали отступы.
Для секции можно добавить правильный заголовок описывающий секцию контента, даже если его нет в макете. Потом правильно его можно убрать с помощью css

2021-05-24 15:16 UTC, ValeryKrukovich commented on index.html
> +      <h2>Давайте дружить, это выгодно!</h2>
Подумай заголовок ли это

2021-05-24 15:18 UTC, ValeryKrukovich requested changes

2021-05-24 15:18 UTC, ValeryKrukovich commented on index.html
>  </html>
По пунктам дз и техническому заданию, верстка всех попапов обязательна. В частности попапа с формой.
У тебя стоит плагин для .editorconfig?

2021-05-26 21:17 UTC, Klyacsa commented
Я пытаюсь сделать пр)

2021-05-27 17:22 UTC, ValeryKrukovich requested changes

2021-05-27 17:22 UTC, ValeryKrukovich commented on catalog.html
> +          <img src="img/catalog/browser-catalog-card.svg" width="360" height="40" alt="Рамка карточки">
Вот тут в карточках, подумай, нужно ли тут свг?
по мне тут можно все сделать с помощью css.
например фоном, а кружочки фоном и border-radius

2021-05-27 17:22 UTC, ValeryKrukovich commented on index.html
> +    <img src="img/footer/map.png" width="1440" height="416" alt="Карта расположения студии">
Тут саму карту по тз можно делать картинкой, но остальные блоки, такие как блок с контактной информацией и кнопкой нужно верстать, это же не карта

2021-05-27 17:22 UTC, ValeryKrukovich commented on index.html
> +      <ul>
Почему поменял порядок расположения? по макету и логике идет с начало список соц.сетей а потом блок текста.
В чем задумка у тебя тут?

2021-05-27 19:32 UTC, Klyacsa commented on index.html
> +      <ul>
Моя задумка: вначале структурно должен быть h2 потом элементы, которые к нему относятся.

2021-05-27 19:33 UTC, Klyacsa commented on catalog.html
> +    <section>
Сделал шаблоны и страницы списками, пагинацию тегами <a>

2021-05-27 19:33 UTC, Klyacsa commented on catalog.html
> +          <img src="img/catalog/browser-catalog-card.svg" width="360" height="40" alt="Рамка карточки">
Понял, принял.

2021-05-27 19:45 UTC, Klyacsa commented on index.html
> +    <img src="img/footer/map.png" width="1440" height="416" alt="Карта расположения студии">
Сверстал.

2021-05-28 07:11 UTC, Klyacsa commented on index.html
> +      <img src="https://via.placeholder.com/150x100" alt="Логотип">
done

2021-05-28 07:11 UTC, Klyacsa commented on index.html
> +      <img src="cart-icon.jpg" alt="Иконка корзины">
done

2021-05-28 07:49 UTC, Klyacsa commented on index.html
> +      <button type="button">УЗНАТЬ БОЛЬШЕ</button>
done.

2021-05-28 07:49 UTC, Klyacsa commented on index.html
> +  </header>
done.

2021-05-28 07:49 UTC, Klyacsa commented on index.html
> +      <h2>Выполняем заказы на разработку:</h2>
done/

2021-05-28 07:50 UTC, Klyacsa commented on index.html
> +    <article>
done.

2021-05-28 07:51 UTC, Klyacsa commented on index.html
> +      <section>
done.

2021-05-28 07:51 UTC, Klyacsa commented on index.html
> +      <h2>Давайте дружить, это выгодно!</h2>
done.

2021-05-28 07:51 UTC, Klyacsa commented on index.html
>  </html>
done.

2021-05-28 07:52 UTC, Klyacsa commented on index.html
> +      <ul>
сделал абзацем

2021-05-29 13:20 UTC, merged