Базовая стилизация главной страницы
htmlacademy-htmlcss/1750369-nerds-31 pull request #3
Opened 2021-05-31 10:28 UTC by Klyacsa

2021-06-01 09:09 UTC, ValeryKrukovich requested changes

2021-06-01 09:09 UTC, ValeryKrukovich commented on css/style.css
> +.main-header-logo {}
Не нужно оставлять в стилях не используемые правила, если их не используешь сейчас.
тут я понимаю что ты будешь использовать эти классы потом, но в реальном проекте у тебя не примут кусок работы с такими штуками, привыкай сразу к этому.
p.s: это относиться к подобному и ниже по коду

2021-06-01 09:09 UTC, ValeryKrukovich commented on css/style.css
> +  background-color: #00CA74;
почему тут и ниже не выносишь название цвета в переменную?
есть критерий, нужно вынести

2021-06-01 09:09 UTC, ValeryKrukovich commented on index.html
>        <div>
сделать отступы внутри дива.
критерий про единообразие

2021-06-01 09:09 UTC, ValeryKrukovich commented on css/style.css
> +:root {
Не нашел в файле подключения шрифтов.

2021-06-01 16:22 UTC, Klyacsa commented on css/style.css
> +span {
done.

2021-06-01 16:34 UTC, Klyacsa commented on css/style.css
> +a {
ok.

2021-06-01 16:34 UTC, Klyacsa commented on css/style.css
> +.main-header-logo {}
done.

2021-06-01 16:42 UTC, Klyacsa commented on index.html
>        <div>
done.

2021-06-01 17:05 UTC, Klyacsa commented on css/style.css
> +  background-color: #00CA74;
done.

2021-06-02 06:51 UTC, ValeryKrukovich approved these changes

2021-06-02 06:51 UTC, merged